### ISSUE TITLE
Add RIZZARR Logo

### ISSUE THREAD

**Issue by RIZZARR** [startupdetroit/www#15]
A link to your logo: http://ashleymwilliams.com/rizzarr/
The city your org is based in: Detroit, MI + Los Angeles, CA
Website link: https://rizzarr.com/ 
The type of supporter you are: Startup

**Comment by shriyash** [comment]
Thanks for the contribution! I've added the logo to the site: http://startupdetroit.co/

Highly encourage you to use #startupdetroit along with any social media post related to the Detroit startup scene and also encourage you to join/share the Slack community we have: http://invite.detroitstartup.community/
