### ISSUE TITLE
Add Saganworks Logo

### ISSUE THREAD

**Issue by lapidus94** [startupdetroit/www#21]
[Logo:](http://saganworks.com/wp-content/uploads/2017/09/SW-logotype-1x-2.png)

Ann Arbor, MI

http://saganworks.com/

Startup

**Comment by shriyash** [comment]
Thanks! Just added the Saganworks logo to the site.

I encourage you to join our community slack and share it within Saganworks! https://startupdetroit.herokuapp.com/
