### ISSUE TITLE
Add Tech Elevator Logo

### ISSUE THREAD

**Issue by jtucholski** [startupdetroit/www#25]
A link to the logo can be found [here](https://res.cloudinary.com/tech-elevator/image/upload/v1554082700/stacked.png)

We are based in Detroit, MI

The link to our website is: https://www.techelevator.com/ and we would be considered a community supporter.

Thank you!

**Comment by jtucholski** [comment]
Hello, about how long does it take to get added to the web page?

**Comment by shriyash** [comment]
Hi @jtucholski - thanks for the contribution! We're a volunteer community of developers and we try to add logos/deploy code every other week. I’ve just pushed an update on the site with the Tech Elevator logo.

I'd check out the Slack community we have as well! Invite link: http://startupdetroit.herokuapp.com/
